---
- name: Set up shared images storage
  hosts: all
  become: true

  vars:
    # specific image to pull
    ansible_image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
    # location of additional image store for shared storage
    additionalimagestores: /var/lib/myee-shared

  roles:
    - shadowman_dev_shared_image_store
