---
- name: Ensure shared image directory exists
  ansible.builtin.file:
    path: "{{ additionalimagestores }}"
    state: directory
    owner: root
    group: root
    mode: a+rx
    recurse: true

- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Pull EE if it does not exist
  containers.podman.podman_image:
    name: "{{ ansible_image }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Ensure correct permissions if image was pulled
  ansible.builtin.command: chmod -R a+rx {{ additionalimagestores }}
  register: permissions
  changed_when: permissions.rc == 0
